// Automatisch aus dem bereitgestellten Spielerpaket übernommen.
// Phase 1 hält Quelldaten bewusst getrennt von der UI-Integration.

export const sourceClassProgressionLevel1To3 = [
  {
    "ruleset": "2014",
    "class_id": "barbarian",
    "class_de": "Barbar",
    "level": 1,
    "proficiency_bonus": 2,
    "primary": "Stärke",
    "priority": "ST > KO > GE > WE",
    "hit_die": "W12",
    "fixed_hp_gain": "7 + KO-Modifikator",
    "saving_throws": "Stärke, Konstitution",
    "armor": "Leichte und mittlere Rüstung, Schilde",
    "weapons": "Einfache und Kriegswaffen",
    "skill_choices": "2: Tierkunde, Athletik, Einschüchtern, Naturkunde, Wahrnehmung oder Überleben",
    "features": "Kampfrausch; Ungepanzerte Verteidigung",
    "resources_and_spellcasting": "2 Rausche, +2 Schaden"
  },
  {
    "ruleset": "2014",
    "class_id": "barbarian",
    "class_de": "Barbar",
    "level": 2,
    "proficiency_bonus": 2,
    "primary": "Stärke",
    "priority": "ST > KO > GE > WE",
    "hit_die": "W12",
    "fixed_hp_gain": "7 + KO-Modifikator",
    "saving_throws": "Stärke, Konstitution",
    "armor": "Leichte und mittlere Rüstung, Schilde",
    "weapons": "Einfache und Kriegswaffen",
    "skill_choices": "2: Tierkunde, Athletik, Einschüchtern, Naturkunde, Wahrnehmung oder Überleben",
    "features": "Rücksichtsloser Angriff; Gefahrengespür",
    "resources_and_spellcasting": "2 Rausche, +2 Schaden"
  },
  {
    "ruleset": "2014",
    "class_id": "barbarian",
    "class_de": "Barbar",
    "level": 3,
    "proficiency_bonus": 2,
    "primary": "Stärke",
    "priority": "ST > KO > GE > WE",
    "hit_die": "W12",
    "fixed_hp_gain": "7 + KO-Modifikator",
    "saving_throws": "Stärke, Konstitution",
    "armor": "Leichte und mittlere Rüstung, Schilde",
    "weapons": "Einfache und Kriegswaffen",
    "skill_choices": "2: Tierkunde, Athletik, Einschüchtern, Naturkunde, Wahrnehmung oder Überleben",
    "features": "Urpfad",
    "resources_and_spellcasting": "3 Rausche, +2 Schaden; Unterklasse"
  },
  {
    "ruleset": "2014",
    "class_id": "bard",
    "class_de": "Barde",
    "level": 1,
    "proficiency_bonus": 2,
    "primary": "Charisma",
    "priority": "CH > GE > KO > WE",
    "hit_die": "W8",
    "fixed_hp_gain": "5 + KO-Modifikator",
    "saving_throws": "Geschicklichkeit, Charisma",
    "armor": "Leichte Rüstung",
    "weapons": "2014: einfache Waffen plus Handarmbrust, Langschwert, Rapier, Kurzschwert; 2024: einfache Waffen",
    "skill_choices": "3 beliebige",
    "features": "Zauberwirken; Bardische Inspiration W6",
    "resources_and_spellcasting": "2 Zaubertricks; 4 bekannte Zauber; Plätze 2"
  },
  {
    "ruleset": "2014",
    "class_id": "bard",
    "class_de": "Barde",
    "level": 2,
    "proficiency_bonus": 2,
    "primary": "Charisma",
    "priority": "CH > GE > KO > WE",
    "hit_die": "W8",
    "fixed_hp_gain": "5 + KO-Modifikator",
    "saving_throws": "Geschicklichkeit, Charisma",
    "armor": "Leichte Rüstung",
    "weapons": "2014: einfache Waffen plus Handarmbrust, Langschwert, Rapier, Kurzschwert; 2024: einfache Waffen",
    "skill_choices": "3 beliebige",
    "features": "Alleskönner; Lied der Erholung W6",
    "resources_and_spellcasting": "2 Zaubertricks; 5 bekannte Zauber; Plätze 3"
  },
  {
    "ruleset": "2014",
    "class_id": "bard",
    "class_de": "Barde",
    "level": 3,
    "proficiency_bonus": 2,
    "primary": "Charisma",
    "priority": "CH > GE > KO > WE",
    "hit_die": "W8",
    "fixed_hp_gain": "5 + KO-Modifikator",
    "saving_throws": "Geschicklichkeit, Charisma",
    "armor": "Leichte Rüstung",
    "weapons": "2014: einfache Waffen plus Handarmbrust, Langschwert, Rapier, Kurzschwert; 2024: einfache Waffen",
    "skill_choices": "3 beliebige",
    "features": "Bardenschule; Expertise",
    "resources_and_spellcasting": "2 Zaubertricks; 6 bekannte Zauber; Plätze 4/2"
  },
  {
    "ruleset": "2014",
    "class_id": "cleric",
    "class_de": "Kleriker",
    "level": 1,
    "proficiency_bonus": 2,
    "primary": "Weisheit",
    "priority": "WE > KO > ST oder GE > CH",
    "hit_die": "W8",
    "fixed_hp_gain": "5 + KO-Modifikator",
    "saving_throws": "Weisheit, Charisma",
    "armor": "Leichte und mittlere Rüstung, Schilde",
    "weapons": "Einfache Waffen",
    "skill_choices": "2: Geschichte, Motiv erkennen, Heilkunde, Überzeugen oder Religion",
    "features": "Zauberwirken; Göttliche Domäne",
    "resources_and_spellcasting": "3 Zaubertricks; vorbereitet WE-Mod + Stufe; Plätze 2"
  },
  {
    "ruleset": "2014",
    "class_id": "cleric",
    "class_de": "Kleriker",
    "level": 2,
    "proficiency_bonus": 2,
    "primary": "Weisheit",
    "priority": "WE > KO > ST oder GE > CH",
    "hit_die": "W8",
    "fixed_hp_gain": "5 + KO-Modifikator",
    "saving_throws": "Weisheit, Charisma",
    "armor": "Leichte und mittlere Rüstung, Schilde",
    "weapons": "Einfache Waffen",
    "skill_choices": "2: Geschichte, Motiv erkennen, Heilkunde, Überzeugen oder Religion",
    "features": "Göttliche Macht fokussieren (1); Domänenoption",
    "resources_and_spellcasting": "3 Zaubertricks; Plätze 3"
  },
  {
    "ruleset": "2014",
    "class_id": "cleric",
    "class_de": "Kleriker",
    "level": 3,
    "proficiency_bonus": 2,
    "primary": "Weisheit",
    "priority": "WE > KO > ST oder GE > CH",
    "hit_die": "W8",
    "fixed_hp_gain": "5 + KO-Modifikator",
    "saving_throws": "Weisheit, Charisma",
    "armor": "Leichte und mittlere Rüstung, Schilde",
    "weapons": "Einfache Waffen",
    "skill_choices": "2: Geschichte, Motiv erkennen, Heilkunde, Überzeugen oder Religion",
    "features": "Zauber 2. Grades",
    "resources_and_spellcasting": "3 Zaubertricks; Plätze 4/2"
  },
  {
    "ruleset": "2014",
    "class_id": "druid",
    "class_de": "Druide",
    "level": 1,
    "proficiency_bonus": 2,
    "primary": "Weisheit",
    "priority": "WE > KO > GE > IN",
    "hit_die": "W8",
    "fixed_hp_gain": "5 + KO-Modifikator",
    "saving_throws": "Intelligenz, Weisheit",
    "armor": "2014: leicht/mittel und Schilde, traditionell kein Metall; 2024: leicht und Schilde",
    "weapons": "2014 eingeschränkte Liste; 2024 einfache Waffen",
    "skill_choices": "2: Arkane Kunde, Tierkunde, Motiv erkennen, Heilkunde, Naturkunde, Wahrnehmung, Religion oder Überleben",
    "features": "Druidisch; Zauberwirken",
    "resources_and_spellcasting": "2 Zaubertricks; vorbereitet WE-Mod + Stufe; Plätze 2"
  },
  {
    "ruleset": "2014",
    "class_id": "druid",
    "class_de": "Druide",
    "level": 2,
    "proficiency_bonus": 2,
    "primary": "Weisheit",
    "priority": "WE > KO > GE > IN",
    "hit_die": "W8",
    "fixed_hp_gain": "5 + KO-Modifikator",
    "saving_throws": "Intelligenz, Weisheit",
    "armor": "2014: leicht/mittel und Schilde, traditionell kein Metall; 2024: leicht und Schilde",
    "weapons": "2014 eingeschränkte Liste; 2024 einfache Waffen",
    "skill_choices": "2: Arkane Kunde, Tierkunde, Motiv erkennen, Heilkunde, Naturkunde, Wahrnehmung, Religion oder Überleben",
    "features": "Tiergestalt (2/Rast); Druidenzirkel",
    "resources_and_spellcasting": "2 Zaubertricks; Plätze 3"
  },
  {
    "ruleset": "2014",
    "class_id": "druid",
    "class_de": "Druide",
    "level": 3,
    "proficiency_bonus": 2,
    "primary": "Weisheit",
    "priority": "WE > KO > GE > IN",
    "hit_die": "W8",
    "fixed_hp_gain": "5 + KO-Modifikator",
    "saving_throws": "Intelligenz, Weisheit",
    "armor": "2014: leicht/mittel und Schilde, traditionell kein Metall; 2024: leicht und Schilde",
    "weapons": "2014 eingeschränkte Liste; 2024 einfache Waffen",
    "skill_choices": "2: Arkane Kunde, Tierkunde, Motiv erkennen, Heilkunde, Naturkunde, Wahrnehmung, Religion oder Überleben",
    "features": "Zauber 2. Grades",
    "resources_and_spellcasting": "2 Zaubertricks; Plätze 4/2"
  },
  {
    "ruleset": "2014",
    "class_id": "fighter",
    "class_de": "Kämpfer",
    "level": 1,
    "proficiency_bonus": 2,
    "primary": "Stärke oder Geschicklichkeit",
    "priority": "ST oder GE > KO > WE; das andere Angriffsattribut meist nachrangig",
    "hit_die": "W10",
    "fixed_hp_gain": "6 + KO-Modifikator",
    "saving_throws": "Stärke, Konstitution",
    "armor": "Alle Rüstungen, Schilde",
    "weapons": "Einfache und Kriegswaffen",
    "skill_choices": "2: Akrobatik, Tierkunde, Athletik, Geschichte, Motiv erkennen, Einschüchtern, Überzeugen, Wahrnehmung oder Überleben",
    "features": "Kampfstil; Durchschnaufen",
    "resources_and_spellcasting": "Durchschnaufen 1/kurze oder lange Rast"
  },
  {
    "ruleset": "2014",
    "class_id": "fighter",
    "class_de": "Kämpfer",
    "level": 2,
    "proficiency_bonus": 2,
    "primary": "Stärke oder Geschicklichkeit",
    "priority": "ST oder GE > KO > WE; das andere Angriffsattribut meist nachrangig",
    "hit_die": "W10",
    "fixed_hp_gain": "6 + KO-Modifikator",
    "saving_throws": "Stärke, Konstitution",
    "armor": "Alle Rüstungen, Schilde",
    "weapons": "Einfache und Kriegswaffen",
    "skill_choices": "2: Akrobatik, Tierkunde, Athletik, Geschichte, Motiv erkennen, Einschüchtern, Überzeugen, Wahrnehmung oder Überleben",
    "features": "Tatendrang",
    "resources_and_spellcasting": "Tatendrang 1/kurze oder lange Rast"
  },
  {
    "ruleset": "2014",
    "class_id": "fighter",
    "class_de": "Kämpfer",
    "level": 3,
    "proficiency_bonus": 2,
    "primary": "Stärke oder Geschicklichkeit",
    "priority": "ST oder GE > KO > WE; das andere Angriffsattribut meist nachrangig",
    "hit_die": "W10",
    "fixed_hp_gain": "6 + KO-Modifikator",
    "saving_throws": "Stärke, Konstitution",
    "armor": "Alle Rüstungen, Schilde",
    "weapons": "Einfache und Kriegswaffen",
    "skill_choices": "2: Akrobatik, Tierkunde, Athletik, Geschichte, Motiv erkennen, Einschüchtern, Überzeugen, Wahrnehmung oder Überleben",
    "features": "Kriegerischer Archetyp",
    "resources_and_spellcasting": "Unterklasse"
  },
  {
    "ruleset": "2014",
    "class_id": "monk",
    "class_de": "Mönch",
    "level": 1,
    "proficiency_bonus": 2,
    "primary": "Geschicklichkeit und Weisheit",
    "priority": "GE > WE > KO > ST",
    "hit_die": "W8",
    "fixed_hp_gain": "5 + KO-Modifikator",
    "saving_throws": "Stärke, Geschicklichkeit",
    "armor": "Keine",
    "weapons": "Einfache Waffen; zusätzlich geeignete leichte Kriegswaffen nach 2024-Regeln",
    "skill_choices": "2: Akrobatik, Athletik, Geschichte, Motiv erkennen, Religion oder Heimlichkeit",
    "features": "Ungepanzerte Verteidigung; Kampfkunst",
    "resources_and_spellcasting": "Kampfkunst W4"
  },
  {
    "ruleset": "2014",
    "class_id": "monk",
    "class_de": "Mönch",
    "level": 2,
    "proficiency_bonus": 2,
    "primary": "Geschicklichkeit und Weisheit",
    "priority": "GE > WE > KO > ST",
    "hit_die": "W8",
    "fixed_hp_gain": "5 + KO-Modifikator",
    "saving_throws": "Stärke, Geschicklichkeit",
    "armor": "Keine",
    "weapons": "Einfache Waffen; zusätzlich geeignete leichte Kriegswaffen nach 2024-Regeln",
    "skill_choices": "2: Akrobatik, Athletik, Geschichte, Motiv erkennen, Religion oder Heimlichkeit",
    "features": "Ki; Ungepanzerte Bewegung",
    "resources_and_spellcasting": "2 Ki; +10 Fuß"
  },
  {
    "ruleset": "2014",
    "class_id": "monk",
    "class_de": "Mönch",
    "level": 3,
    "proficiency_bonus": 2,
    "primary": "Geschicklichkeit und Weisheit",
    "priority": "GE > WE > KO > ST",
    "hit_die": "W8",
    "fixed_hp_gain": "5 + KO-Modifikator",
    "saving_throws": "Stärke, Geschicklichkeit",
    "armor": "Keine",
    "weapons": "Einfache Waffen; zusätzlich geeignete leichte Kriegswaffen nach 2024-Regeln",
    "skill_choices": "2: Akrobatik, Athletik, Geschichte, Motiv erkennen, Religion oder Heimlichkeit",
    "features": "Mönchstradition; Geschosse abwehren",
    "resources_and_spellcasting": "3 Ki; Kampfkunst W4; Unterklasse"
  },
  {
    "ruleset": "2014",
    "class_id": "paladin",
    "class_de": "Paladin",
    "level": 1,
    "proficiency_bonus": 2,
    "primary": "Stärke und Charisma",
    "priority": "ST > CH > KO > WE; GE-Paladine optional",
    "hit_die": "W10",
    "fixed_hp_gain": "6 + KO-Modifikator",
    "saving_throws": "Weisheit, Charisma",
    "armor": "Alle Rüstungen, Schilde",
    "weapons": "Einfache und Kriegswaffen",
    "skill_choices": "2: Athletik, Motiv erkennen, Einschüchtern, Heilkunde, Überzeugen oder Religion",
    "features": "Göttliches Gespür; Handauflegen",
    "resources_and_spellcasting": "Gespür 1+CH-Mod/LR; Heilpool 5"
  },
  {
    "ruleset": "2014",
    "class_id": "paladin",
    "class_de": "Paladin",
    "level": 2,
    "proficiency_bonus": 2,
    "primary": "Stärke und Charisma",
    "priority": "ST > CH > KO > WE; GE-Paladine optional",
    "hit_die": "W10",
    "fixed_hp_gain": "6 + KO-Modifikator",
    "saving_throws": "Weisheit, Charisma",
    "armor": "Alle Rüstungen, Schilde",
    "weapons": "Einfache und Kriegswaffen",
    "skill_choices": "2: Athletik, Motiv erkennen, Einschüchtern, Heilkunde, Überzeugen oder Religion",
    "features": "Kampfstil; Zauberwirken; Göttliches Niederstrecken",
    "resources_and_spellcasting": "Heilpool 10; Plätze 2"
  },
  {
    "ruleset": "2014",
    "class_id": "paladin",
    "class_de": "Paladin",
    "level": 3,
    "proficiency_bonus": 2,
    "primary": "Stärke und Charisma",
    "priority": "ST > CH > KO > WE; GE-Paladine optional",
    "hit_die": "W10",
    "fixed_hp_gain": "6 + KO-Modifikator",
    "saving_throws": "Weisheit, Charisma",
    "armor": "Alle Rüstungen, Schilde",
    "weapons": "Einfache und Kriegswaffen",
    "skill_choices": "2: Athletik, Motiv erkennen, Einschüchtern, Heilkunde, Überzeugen oder Religion",
    "features": "Göttliche Gesundheit; Heiliger Eid",
    "resources_and_spellcasting": "Heilpool 15; Plätze 3; Unterklasse/Göttliche Macht fokussieren"
  },
  {
    "ruleset": "2014",
    "class_id": "ranger",
    "class_de": "Waldläufer",
    "level": 1,
    "proficiency_bonus": 2,
    "primary": "Geschicklichkeit und Weisheit",
    "priority": "GE > WE > KO > ST",
    "hit_die": "W10",
    "fixed_hp_gain": "6 + KO-Modifikator",
    "saving_throws": "Stärke, Geschicklichkeit",
    "armor": "Leichte und mittlere Rüstung, Schilde",
    "weapons": "Einfache und Kriegswaffen",
    "skill_choices": "3: Tierkunde, Athletik, Motiv erkennen, Nachforschungen, Naturkunde, Wahrnehmung, Heimlichkeit oder Überleben",
    "features": "Erzfeind; Natürlicher Entdecker",
    "resources_and_spellcasting": "Erkundungsentscheidungen"
  },
  {
    "ruleset": "2014",
    "class_id": "ranger",
    "class_de": "Waldläufer",
    "level": 2,
    "proficiency_bonus": 2,
    "primary": "Geschicklichkeit und Weisheit",
    "priority": "GE > WE > KO > ST",
    "hit_die": "W10",
    "fixed_hp_gain": "6 + KO-Modifikator",
    "saving_throws": "Stärke, Geschicklichkeit",
    "armor": "Leichte und mittlere Rüstung, Schilde",
    "weapons": "Einfache und Kriegswaffen",
    "skill_choices": "3: Tierkunde, Athletik, Motiv erkennen, Nachforschungen, Naturkunde, Wahrnehmung, Heimlichkeit oder Überleben",
    "features": "Kampfstil; Zauberwirken",
    "resources_and_spellcasting": "2 bekannte Zauber; Plätze 2"
  },
  {
    "ruleset": "2014",
    "class_id": "ranger",
    "class_de": "Waldläufer",
    "level": 3,
    "proficiency_bonus": 2,
    "primary": "Geschicklichkeit und Weisheit",
    "priority": "GE > WE > KO > ST",
    "hit_die": "W10",
    "fixed_hp_gain": "6 + KO-Modifikator",
    "saving_throws": "Stärke, Geschicklichkeit",
    "armor": "Leichte und mittlere Rüstung, Schilde",
    "weapons": "Einfache und Kriegswaffen",
    "skill_choices": "3: Tierkunde, Athletik, Motiv erkennen, Nachforschungen, Naturkunde, Wahrnehmung, Heimlichkeit oder Überleben",
    "features": "Waldläuferarchetyp; Urbewusstsein",
    "resources_and_spellcasting": "3 bekannte Zauber; Plätze 3; Unterklasse"
  },
  {
    "ruleset": "2014",
    "class_id": "rogue",
    "class_de": "Schurke",
    "level": 1,
    "proficiency_bonus": 2,
    "primary": "Geschicklichkeit",
    "priority": "GE > KO > WE oder IN > CH",
    "hit_die": "W8",
    "fixed_hp_gain": "5 + KO-Modifikator",
    "saving_throws": "Geschicklichkeit, Intelligenz",
    "armor": "Leichte Rüstung",
    "weapons": "2014: einfache plus ausgewählte; 2024: einfache und Kriegswaffen mit Finesse oder Leicht",
    "skill_choices": "4: Akrobatik, Athletik, Täuschen, Motiv erkennen, Einschüchtern, Nachforschungen, Wahrnehmung, Überzeugen/Auftreten, Fingerfertigkeit oder Heimlichkeit",
    "features": "Expertise; Hinterhältiger Angriff; Diebeszeichen",
    "resources_and_spellcasting": "Hinterhältiger Angriff 1W6"
  },
  {
    "ruleset": "2014",
    "class_id": "rogue",
    "class_de": "Schurke",
    "level": 2,
    "proficiency_bonus": 2,
    "primary": "Geschicklichkeit",
    "priority": "GE > KO > WE oder IN > CH",
    "hit_die": "W8",
    "fixed_hp_gain": "5 + KO-Modifikator",
    "saving_throws": "Geschicklichkeit, Intelligenz",
    "armor": "Leichte Rüstung",
    "weapons": "2014: einfache plus ausgewählte; 2024: einfache und Kriegswaffen mit Finesse oder Leicht",
    "skill_choices": "4: Akrobatik, Athletik, Täuschen, Motiv erkennen, Einschüchtern, Nachforschungen, Wahrnehmung, Überzeugen/Auftreten, Fingerfertigkeit oder Heimlichkeit",
    "features": "Raffinierte Aktion",
    "resources_and_spellcasting": "Hinterhältiger Angriff 1W6"
  },
  {
    "ruleset": "2014",
    "class_id": "rogue",
    "class_de": "Schurke",
    "level": 3,
    "proficiency_bonus": 2,
    "primary": "Geschicklichkeit",
    "priority": "GE > KO > WE oder IN > CH",
    "hit_die": "W8",
    "fixed_hp_gain": "5 + KO-Modifikator",
    "saving_throws": "Geschicklichkeit, Intelligenz",
    "armor": "Leichte Rüstung",
    "weapons": "2014: einfache plus ausgewählte; 2024: einfache und Kriegswaffen mit Finesse oder Leicht",
    "skill_choices": "4: Akrobatik, Athletik, Täuschen, Motiv erkennen, Einschüchtern, Nachforschungen, Wahrnehmung, Überzeugen/Auftreten, Fingerfertigkeit oder Heimlichkeit",
    "features": "Schurkenarchetyp",
    "resources_and_spellcasting": "Hinterhältiger Angriff 2W6; Unterklasse"
  },
  {
    "ruleset": "2014",
    "class_id": "sorcerer",
    "class_de": "Zauberer",
    "level": 1,
    "proficiency_bonus": 2,
    "primary": "Charisma",
    "priority": "CH > KO > GE > WE",
    "hit_die": "W6",
    "fixed_hp_gain": "4 + KO-Modifikator",
    "saving_throws": "Konstitution, Charisma",
    "armor": "Keine",
    "weapons": "2014 eingeschränkte Liste; 2024 einfache Waffen",
    "skill_choices": "2: Arkane Kunde, Täuschen, Motiv erkennen, Einschüchtern, Überzeugen oder Religion",
    "features": "Zauberwirken; Magischer Ursprung",
    "resources_and_spellcasting": "4 Zaubertricks; 2 bekannte Zauber; Plätze 2"
  },
  {
    "ruleset": "2014",
    "class_id": "sorcerer",
    "class_de": "Zauberer",
    "level": 2,
    "proficiency_bonus": 2,
    "primary": "Charisma",
    "priority": "CH > KO > GE > WE",
    "hit_die": "W6",
    "fixed_hp_gain": "4 + KO-Modifikator",
    "saving_throws": "Konstitution, Charisma",
    "armor": "Keine",
    "weapons": "2014 eingeschränkte Liste; 2024 einfache Waffen",
    "skill_choices": "2: Arkane Kunde, Täuschen, Motiv erkennen, Einschüchtern, Überzeugen oder Religion",
    "features": "Quelle der Magie",
    "resources_and_spellcasting": "2 Zaubereipunkte; 3 bekannte Zauber; Plätze 3"
  },
  {
    "ruleset": "2014",
    "class_id": "sorcerer",
    "class_de": "Zauberer",
    "level": 3,
    "proficiency_bonus": 2,
    "primary": "Charisma",
    "priority": "CH > KO > GE > WE",
    "hit_die": "W6",
    "fixed_hp_gain": "4 + KO-Modifikator",
    "saving_throws": "Konstitution, Charisma",
    "armor": "Keine",
    "weapons": "2014 eingeschränkte Liste; 2024 einfache Waffen",
    "skill_choices": "2: Arkane Kunde, Täuschen, Motiv erkennen, Einschüchtern, Überzeugen oder Religion",
    "features": "Metamagie (2 Optionen)",
    "resources_and_spellcasting": "3 Zaubereipunkte; 4 bekannte Zauber; Plätze 4/2"
  },
  {
    "ruleset": "2014",
    "class_id": "warlock",
    "class_de": "Hexenmeister",
    "level": 1,
    "proficiency_bonus": 2,
    "primary": "Charisma",
    "priority": "CH > KO > GE > WE",
    "hit_die": "W8",
    "fixed_hp_gain": "5 + KO-Modifikator",
    "saving_throws": "Weisheit, Charisma",
    "armor": "Leichte Rüstung",
    "weapons": "Einfache Waffen",
    "skill_choices": "2: Arkane Kunde, Täuschen, Geschichte, Einschüchtern, Nachforschungen, Naturkunde oder Religion",
    "features": "Jenseitiger Patron; Paktmagie",
    "resources_and_spellcasting": "2 Zaubertricks; 2 bekannte Zauber; 1 Platz Grad 1"
  },
  {
    "ruleset": "2014",
    "class_id": "warlock",
    "class_de": "Hexenmeister",
    "level": 2,
    "proficiency_bonus": 2,
    "primary": "Charisma",
    "priority": "CH > KO > GE > WE",
    "hit_die": "W8",
    "fixed_hp_gain": "5 + KO-Modifikator",
    "saving_throws": "Weisheit, Charisma",
    "armor": "Leichte Rüstung",
    "weapons": "Einfache Waffen",
    "skill_choices": "2: Arkane Kunde, Täuschen, Geschichte, Einschüchtern, Nachforschungen, Naturkunde oder Religion",
    "features": "Unheimliche Anrufungen (2)",
    "resources_and_spellcasting": "3 bekannte Zauber; 2 Plätze Grad 1"
  },
  {
    "ruleset": "2014",
    "class_id": "warlock",
    "class_de": "Hexenmeister",
    "level": 3,
    "proficiency_bonus": 2,
    "primary": "Charisma",
    "priority": "CH > KO > GE > WE",
    "hit_die": "W8",
    "fixed_hp_gain": "5 + KO-Modifikator",
    "saving_throws": "Weisheit, Charisma",
    "armor": "Leichte Rüstung",
    "weapons": "Einfache Waffen",
    "skill_choices": "2: Arkane Kunde, Täuschen, Geschichte, Einschüchtern, Nachforschungen, Naturkunde oder Religion",
    "features": "Paktsegen",
    "resources_and_spellcasting": "4 bekannte Zauber; 2 Plätze Grad 2"
  },
  {
    "ruleset": "2014",
    "class_id": "wizard",
    "class_de": "Magier",
    "level": 1,
    "proficiency_bonus": 2,
    "primary": "Intelligenz",
    "priority": "IN > KO > GE > WE",
    "hit_die": "W6",
    "fixed_hp_gain": "4 + KO-Modifikator",
    "saving_throws": "Intelligenz, Weisheit",
    "armor": "Keine",
    "weapons": "2014 eingeschränkte Liste; 2024 einfache Waffen",
    "skill_choices": "2: Arkane Kunde, Geschichte, Motiv erkennen, Nachforschungen, Heilkunde, Naturkunde oder Religion",
    "features": "Zauberwirken; Arkane Erholung",
    "resources_and_spellcasting": "3 Zaubertricks; Zauberbuch 6; vorbereitet IN-Mod + Stufe; Plätze 2"
  },
  {
    "ruleset": "2014",
    "class_id": "wizard",
    "class_de": "Magier",
    "level": 2,
    "proficiency_bonus": 2,
    "primary": "Intelligenz",
    "priority": "IN > KO > GE > WE",
    "hit_die": "W6",
    "fixed_hp_gain": "4 + KO-Modifikator",
    "saving_throws": "Intelligenz, Weisheit",
    "armor": "Keine",
    "weapons": "2014 eingeschränkte Liste; 2024 einfache Waffen",
    "skill_choices": "2: Arkane Kunde, Geschichte, Motiv erkennen, Nachforschungen, Heilkunde, Naturkunde oder Religion",
    "features": "Arkane Tradition",
    "resources_and_spellcasting": "Zauberbuch +2; Plätze 3"
  },
  {
    "ruleset": "2014",
    "class_id": "wizard",
    "class_de": "Magier",
    "level": 3,
    "proficiency_bonus": 2,
    "primary": "Intelligenz",
    "priority": "IN > KO > GE > WE",
    "hit_die": "W6",
    "fixed_hp_gain": "4 + KO-Modifikator",
    "saving_throws": "Intelligenz, Weisheit",
    "armor": "Keine",
    "weapons": "2014 eingeschränkte Liste; 2024 einfache Waffen",
    "skill_choices": "2: Arkane Kunde, Geschichte, Motiv erkennen, Nachforschungen, Heilkunde, Naturkunde oder Religion",
    "features": "Zauber 2. Grades",
    "resources_and_spellcasting": "Zauberbuch +2; Plätze 4/2"
  },
  {
    "ruleset": "2024/SRD-5.2.1",
    "class_id": "barbarian",
    "class_de": "Barbar",
    "level": 1,
    "proficiency_bonus": 2,
    "primary": "Stärke",
    "priority": "ST > KO > GE > WE",
    "hit_die": "W12",
    "fixed_hp_gain": "7 + KO-Modifikator",
    "saving_throws": "Stärke, Konstitution",
    "armor": "Leichte und mittlere Rüstung, Schilde",
    "weapons": "Einfache und Kriegswaffen",
    "skill_choices": "2: Tierkunde, Athletik, Einschüchtern, Naturkunde, Wahrnehmung oder Überleben",
    "features": "Kampfrausch; Ungepanzerte Verteidigung; Waffenmeisterschaft",
    "resources_and_spellcasting": "2 Rausche; +2 Schaden; 2 Meisterschaften"
  },
  {
    "ruleset": "2024/SRD-5.2.1",
    "class_id": "barbarian",
    "class_de": "Barbar",
    "level": 2,
    "proficiency_bonus": 2,
    "primary": "Stärke",
    "priority": "ST > KO > GE > WE",
    "hit_die": "W12",
    "fixed_hp_gain": "7 + KO-Modifikator",
    "saving_throws": "Stärke, Konstitution",
    "armor": "Leichte und mittlere Rüstung, Schilde",
    "weapons": "Einfache und Kriegswaffen",
    "skill_choices": "2: Tierkunde, Athletik, Einschüchtern, Naturkunde, Wahrnehmung oder Überleben",
    "features": "Gefahrengespür; Rücksichtsloser Angriff",
    "resources_and_spellcasting": "2 Rausche"
  },
  {
    "ruleset": "2024/SRD-5.2.1",
    "class_id": "barbarian",
    "class_de": "Barbar",
    "level": 3,
    "proficiency_bonus": 2,
    "primary": "Stärke",
    "priority": "ST > KO > GE > WE",
    "hit_die": "W12",
    "fixed_hp_gain": "7 + KO-Modifikator",
    "saving_throws": "Stärke, Konstitution",
    "armor": "Leichte und mittlere Rüstung, Schilde",
    "weapons": "Einfache und Kriegswaffen",
    "skill_choices": "2: Tierkunde, Athletik, Einschüchtern, Naturkunde, Wahrnehmung oder Überleben",
    "features": "Barbarenunterklasse; Urwissen",
    "resources_and_spellcasting": "3 Rausche; Unterklasse"
  },
  {
    "ruleset": "2024/SRD-5.2.1",
    "class_id": "bard",
    "class_de": "Barde",
    "level": 1,
    "proficiency_bonus": 2,
    "primary": "Charisma",
    "priority": "CH > GE > KO > WE",
    "hit_die": "W8",
    "fixed_hp_gain": "5 + KO-Modifikator",
    "saving_throws": "Geschicklichkeit, Charisma",
    "armor": "Leichte Rüstung",
    "weapons": "2014: einfache Waffen plus Handarmbrust, Langschwert, Rapier, Kurzschwert; 2024: einfache Waffen",
    "skill_choices": "3 beliebige",
    "features": "Bardische Inspiration; Zauberwirken",
    "resources_and_spellcasting": "2 Zaubertricks; 4 vorbereitete Zauber; Plätze 2"
  },
  {
    "ruleset": "2024/SRD-5.2.1",
    "class_id": "bard",
    "class_de": "Barde",
    "level": 2,
    "proficiency_bonus": 2,
    "primary": "Charisma",
    "priority": "CH > GE > KO > WE",
    "hit_die": "W8",
    "fixed_hp_gain": "5 + KO-Modifikator",
    "saving_throws": "Geschicklichkeit, Charisma",
    "armor": "Leichte Rüstung",
    "weapons": "2014: einfache Waffen plus Handarmbrust, Langschwert, Rapier, Kurzschwert; 2024: einfache Waffen",
    "skill_choices": "3 beliebige",
    "features": "Expertise; Alleskönner",
    "resources_and_spellcasting": "2 Zaubertricks; 5 vorbereitete Zauber; Plätze 3"
  },
  {
    "ruleset": "2024/SRD-5.2.1",
    "class_id": "bard",
    "class_de": "Barde",
    "level": 3,
    "proficiency_bonus": 2,
    "primary": "Charisma",
    "priority": "CH > GE > KO > WE",
    "hit_die": "W8",
    "fixed_hp_gain": "5 + KO-Modifikator",
    "saving_throws": "Geschicklichkeit, Charisma",
    "armor": "Leichte Rüstung",
    "weapons": "2014: einfache Waffen plus Handarmbrust, Langschwert, Rapier, Kurzschwert; 2024: einfache Waffen",
    "skill_choices": "3 beliebige",
    "features": "Bardenunterklasse",
    "resources_and_spellcasting": "2 Zaubertricks; 6 vorbereitete Zauber; Plätze 4/2"
  },
  {
    "ruleset": "2024/SRD-5.2.1",
    "class_id": "cleric",
    "class_de": "Kleriker",
    "level": 1,
    "proficiency_bonus": 2,
    "primary": "Weisheit",
    "priority": "WE > KO > ST oder GE > CH",
    "hit_die": "W8",
    "fixed_hp_gain": "5 + KO-Modifikator",
    "saving_throws": "Weisheit, Charisma",
    "armor": "Leichte und mittlere Rüstung, Schilde",
    "weapons": "Einfache Waffen",
    "skill_choices": "2: Geschichte, Motiv erkennen, Heilkunde, Überzeugen oder Religion",
    "features": "Zauberwirken; Göttlicher Orden",
    "resources_and_spellcasting": "3 Zaubertricks; 4 vorbereitete Zauber; Plätze 2"
  },
  {
    "ruleset": "2024/SRD-5.2.1",
    "class_id": "cleric",
    "class_de": "Kleriker",
    "level": 2,
    "proficiency_bonus": 2,
    "primary": "Weisheit",
    "priority": "WE > KO > ST oder GE > CH",
    "hit_die": "W8",
    "fixed_hp_gain": "5 + KO-Modifikator",
    "saving_throws": "Weisheit, Charisma",
    "armor": "Leichte und mittlere Rüstung, Schilde",
    "weapons": "Einfache Waffen",
    "skill_choices": "2: Geschichte, Motiv erkennen, Heilkunde, Überzeugen oder Religion",
    "features": "Göttliche Macht fokussieren",
    "resources_and_spellcasting": "3 Zaubertricks; 5 vorbereitete Zauber; Plätze 3"
  },
  {
    "ruleset": "2024/SRD-5.2.1",
    "class_id": "cleric",
    "class_de": "Kleriker",
    "level": 3,
    "proficiency_bonus": 2,
    "primary": "Weisheit",
    "priority": "WE > KO > ST oder GE > CH",
    "hit_die": "W8",
    "fixed_hp_gain": "5 + KO-Modifikator",
    "saving_throws": "Weisheit, Charisma",
    "armor": "Leichte und mittlere Rüstung, Schilde",
    "weapons": "Einfache Waffen",
    "skill_choices": "2: Geschichte, Motiv erkennen, Heilkunde, Überzeugen oder Religion",
    "features": "Klerikerunterklasse",
    "resources_and_spellcasting": "3 Zaubertricks; 6 vorbereitete Zauber; Plätze 4/2"
  },
  {
    "ruleset": "2024/SRD-5.2.1",
    "class_id": "druid",
    "class_de": "Druide",
    "level": 1,
    "proficiency_bonus": 2,
    "primary": "Weisheit",
    "priority": "WE > KO > GE > IN",
    "hit_die": "W8",
    "fixed_hp_gain": "5 + KO-Modifikator",
    "saving_throws": "Intelligenz, Weisheit",
    "armor": "2014: leicht/mittel und Schilde, traditionell kein Metall; 2024: leicht und Schilde",
    "weapons": "2014 eingeschränkte Liste; 2024 einfache Waffen",
    "skill_choices": "2: Arkane Kunde, Tierkunde, Motiv erkennen, Heilkunde, Naturkunde, Wahrnehmung, Religion oder Überleben",
    "features": "Zauberwirken; Druidisch; Urorden",
    "resources_and_spellcasting": "2 Zaubertricks; 4 vorbereitete Zauber; Plätze 2"
  },
  {
    "ruleset": "2024/SRD-5.2.1",
    "class_id": "druid",
    "class_de": "Druide",
    "level": 2,
    "proficiency_bonus": 2,
    "primary": "Weisheit",
    "priority": "WE > KO > GE > IN",
    "hit_die": "W8",
    "fixed_hp_gain": "5 + KO-Modifikator",
    "saving_throws": "Intelligenz, Weisheit",
    "armor": "2014: leicht/mittel und Schilde, traditionell kein Metall; 2024: leicht und Schilde",
    "weapons": "2014 eingeschränkte Liste; 2024 einfache Waffen",
    "skill_choices": "2: Arkane Kunde, Tierkunde, Motiv erkennen, Heilkunde, Naturkunde, Wahrnehmung, Religion oder Überleben",
    "features": "Tiergestalt; Wilder Gefährte",
    "resources_and_spellcasting": "2 Tiergestalten; 5 vorbereitete Zauber; Plätze 3"
  },
  {
    "ruleset": "2024/SRD-5.2.1",
    "class_id": "druid",
    "class_de": "Druide",
    "level": 3,
    "proficiency_bonus": 2,
    "primary": "Weisheit",
    "priority": "WE > KO > GE > IN",
    "hit_die": "W8",
    "fixed_hp_gain": "5 + KO-Modifikator",
    "saving_throws": "Intelligenz, Weisheit",
    "armor": "2014: leicht/mittel und Schilde, traditionell kein Metall; 2024: leicht und Schilde",
    "weapons": "2014 eingeschränkte Liste; 2024 einfache Waffen",
    "skill_choices": "2: Arkane Kunde, Tierkunde, Motiv erkennen, Heilkunde, Naturkunde, Wahrnehmung, Religion oder Überleben",
    "features": "Druidenunterklasse",
    "resources_and_spellcasting": "2 Tiergestalten; 6 vorbereitete Zauber; Plätze 4/2"
  },
  {
    "ruleset": "2024/SRD-5.2.1",
    "class_id": "fighter",
    "class_de": "Kämpfer",
    "level": 1,
    "proficiency_bonus": 2,
    "primary": "Stärke oder Geschicklichkeit",
    "priority": "ST oder GE > KO > WE; das andere Angriffsattribut meist nachrangig",
    "hit_die": "W10",
    "fixed_hp_gain": "6 + KO-Modifikator",
    "saving_throws": "Stärke, Konstitution",
    "armor": "Alle Rüstungen, Schilde",
    "weapons": "Einfache und Kriegswaffen",
    "skill_choices": "2: Akrobatik, Tierkunde, Athletik, Geschichte, Motiv erkennen, Einschüchtern, Überzeugen, Wahrnehmung oder Überleben",
    "features": "Kampfstil; Durchschnaufen; Waffenmeisterschaft",
    "resources_and_spellcasting": "2 Durchschnaufen; 3 Meisterschaften"
  },
  {
    "ruleset": "2024/SRD-5.2.1",
    "class_id": "fighter",
    "class_de": "Kämpfer",
    "level": 2,
    "proficiency_bonus": 2,
    "primary": "Stärke oder Geschicklichkeit",
    "priority": "ST oder GE > KO > WE; das andere Angriffsattribut meist nachrangig",
    "hit_die": "W10",
    "fixed_hp_gain": "6 + KO-Modifikator",
    "saving_throws": "Stärke, Konstitution",
    "armor": "Alle Rüstungen, Schilde",
    "weapons": "Einfache und Kriegswaffen",
    "skill_choices": "2: Akrobatik, Tierkunde, Athletik, Geschichte, Motiv erkennen, Einschüchtern, Überzeugen, Wahrnehmung oder Überleben",
    "features": "Tatendrang; Taktischer Verstand",
    "resources_and_spellcasting": "Tatendrang 1; 2 Durchschnaufen"
  },
  {
    "ruleset": "2024/SRD-5.2.1",
    "class_id": "fighter",
    "class_de": "Kämpfer",
    "level": 3,
    "proficiency_bonus": 2,
    "primary": "Stärke oder Geschicklichkeit",
    "priority": "ST oder GE > KO > WE; das andere Angriffsattribut meist nachrangig",
    "hit_die": "W10",
    "fixed_hp_gain": "6 + KO-Modifikator",
    "saving_throws": "Stärke, Konstitution",
    "armor": "Alle Rüstungen, Schilde",
    "weapons": "Einfache und Kriegswaffen",
    "skill_choices": "2: Akrobatik, Tierkunde, Athletik, Geschichte, Motiv erkennen, Einschüchtern, Überzeugen, Wahrnehmung oder Überleben",
    "features": "Kämpferunterklasse",
    "resources_and_spellcasting": "Unterklasse"
  },
  {
    "ruleset": "2024/SRD-5.2.1",
    "class_id": "monk",
    "class_de": "Mönch",
    "level": 1,
    "proficiency_bonus": 2,
    "primary": "Geschicklichkeit und Weisheit",
    "priority": "GE > WE > KO > ST",
    "hit_die": "W8",
    "fixed_hp_gain": "5 + KO-Modifikator",
    "saving_throws": "Stärke, Geschicklichkeit",
    "armor": "Keine",
    "weapons": "Einfache Waffen; zusätzlich geeignete leichte Kriegswaffen nach 2024-Regeln",
    "skill_choices": "2: Akrobatik, Athletik, Geschichte, Motiv erkennen, Religion oder Heimlichkeit",
    "features": "Kampfkunst; Ungepanzerte Verteidigung",
    "resources_and_spellcasting": "Kampfkunst W6"
  },
  {
    "ruleset": "2024/SRD-5.2.1",
    "class_id": "monk",
    "class_de": "Mönch",
    "level": 2,
    "proficiency_bonus": 2,
    "primary": "Geschicklichkeit und Weisheit",
    "priority": "GE > WE > KO > ST",
    "hit_die": "W8",
    "fixed_hp_gain": "5 + KO-Modifikator",
    "saving_throws": "Stärke, Geschicklichkeit",
    "armor": "Keine",
    "weapons": "Einfache Waffen; zusätzlich geeignete leichte Kriegswaffen nach 2024-Regeln",
    "skill_choices": "2: Akrobatik, Athletik, Geschichte, Motiv erkennen, Religion oder Heimlichkeit",
    "features": "Mönchsfokus; Ungepanzerte Bewegung; Unheimlicher Stoffwechsel",
    "resources_and_spellcasting": "2 Fokuspunkte; +10 Fuß"
  },
  {
    "ruleset": "2024/SRD-5.2.1",
    "class_id": "monk",
    "class_de": "Mönch",
    "level": 3,
    "proficiency_bonus": 2,
    "primary": "Geschicklichkeit und Weisheit",
    "priority": "GE > WE > KO > ST",
    "hit_die": "W8",
    "fixed_hp_gain": "5 + KO-Modifikator",
    "saving_throws": "Stärke, Geschicklichkeit",
    "armor": "Keine",
    "weapons": "Einfache Waffen; zusätzlich geeignete leichte Kriegswaffen nach 2024-Regeln",
    "skill_choices": "2: Akrobatik, Athletik, Geschichte, Motiv erkennen, Religion oder Heimlichkeit",
    "features": "Angriffe abwehren; Mönchsunterklasse",
    "resources_and_spellcasting": "3 Fokuspunkte; Unterklasse"
  },
  {
    "ruleset": "2024/SRD-5.2.1",
    "class_id": "paladin",
    "class_de": "Paladin",
    "level": 1,
    "proficiency_bonus": 2,
    "primary": "Stärke und Charisma",
    "priority": "ST > CH > KO > WE; GE-Paladine optional",
    "hit_die": "W10",
    "fixed_hp_gain": "6 + KO-Modifikator",
    "saving_throws": "Weisheit, Charisma",
    "armor": "Alle Rüstungen, Schilde",
    "weapons": "Einfache und Kriegswaffen",
    "skill_choices": "2: Athletik, Motiv erkennen, Einschüchtern, Heilkunde, Überzeugen oder Religion",
    "features": "Handauflegen; Zauberwirken; Waffenmeisterschaft",
    "resources_and_spellcasting": "2 vorbereitete Zauber; Plätze 2"
  },
  {
    "ruleset": "2024/SRD-5.2.1",
    "class_id": "paladin",
    "class_de": "Paladin",
    "level": 2,
    "proficiency_bonus": 2,
    "primary": "Stärke und Charisma",
    "priority": "ST > CH > KO > WE; GE-Paladine optional",
    "hit_die": "W10",
    "fixed_hp_gain": "6 + KO-Modifikator",
    "saving_throws": "Weisheit, Charisma",
    "armor": "Alle Rüstungen, Schilde",
    "weapons": "Einfache und Kriegswaffen",
    "skill_choices": "2: Athletik, Motiv erkennen, Einschüchtern, Heilkunde, Überzeugen oder Religion",
    "features": "Kampfstil; Bannschlag des Paladins",
    "resources_and_spellcasting": "3 vorbereitete Zauber; Plätze 2"
  },
  {
    "ruleset": "2024/SRD-5.2.1",
    "class_id": "paladin",
    "class_de": "Paladin",
    "level": 3,
    "proficiency_bonus": 2,
    "primary": "Stärke und Charisma",
    "priority": "ST > CH > KO > WE; GE-Paladine optional",
    "hit_die": "W10",
    "fixed_hp_gain": "6 + KO-Modifikator",
    "saving_throws": "Weisheit, Charisma",
    "armor": "Alle Rüstungen, Schilde",
    "weapons": "Einfache und Kriegswaffen",
    "skill_choices": "2: Athletik, Motiv erkennen, Einschüchtern, Heilkunde, Überzeugen oder Religion",
    "features": "Göttliche Macht fokussieren; Paladinunterklasse",
    "resources_and_spellcasting": "2 Anwendungen; 4 vorbereitete Zauber; Plätze 3"
  },
  {
    "ruleset": "2024/SRD-5.2.1",
    "class_id": "ranger",
    "class_de": "Waldläufer",
    "level": 1,
    "proficiency_bonus": 2,
    "primary": "Geschicklichkeit und Weisheit",
    "priority": "GE > WE > KO > ST",
    "hit_die": "W10",
    "fixed_hp_gain": "6 + KO-Modifikator",
    "saving_throws": "Stärke, Geschicklichkeit",
    "armor": "Leichte und mittlere Rüstung, Schilde",
    "weapons": "Einfache und Kriegswaffen",
    "skill_choices": "3: Tierkunde, Athletik, Motiv erkennen, Nachforschungen, Naturkunde, Wahrnehmung, Heimlichkeit oder Überleben",
    "features": "Zauberwirken; Erzfeind; Waffenmeisterschaft",
    "resources_and_spellcasting": "2 vorbereitete Zauber; Plätze 2; 2 Meisterschaften"
  },
  {
    "ruleset": "2024/SRD-5.2.1",
    "class_id": "ranger",
    "class_de": "Waldläufer",
    "level": 2,
    "proficiency_bonus": 2,
    "primary": "Geschicklichkeit und Weisheit",
    "priority": "GE > WE > KO > ST",
    "hit_die": "W10",
    "fixed_hp_gain": "6 + KO-Modifikator",
    "saving_throws": "Stärke, Geschicklichkeit",
    "armor": "Leichte und mittlere Rüstung, Schilde",
    "weapons": "Einfache und Kriegswaffen",
    "skill_choices": "3: Tierkunde, Athletik, Motiv erkennen, Nachforschungen, Naturkunde, Wahrnehmung, Heimlichkeit oder Überleben",
    "features": "Geschickter Entdecker; Kampfstil",
    "resources_and_spellcasting": "3 vorbereitete Zauber; Plätze 2"
  },
  {
    "ruleset": "2024/SRD-5.2.1",
    "class_id": "ranger",
    "class_de": "Waldläufer",
    "level": 3,
    "proficiency_bonus": 2,
    "primary": "Geschicklichkeit und Weisheit",
    "priority": "GE > WE > KO > ST",
    "hit_die": "W10",
    "fixed_hp_gain": "6 + KO-Modifikator",
    "saving_throws": "Stärke, Geschicklichkeit",
    "armor": "Leichte und mittlere Rüstung, Schilde",
    "weapons": "Einfache und Kriegswaffen",
    "skill_choices": "3: Tierkunde, Athletik, Motiv erkennen, Nachforschungen, Naturkunde, Wahrnehmung, Heimlichkeit oder Überleben",
    "features": "Waldläuferunterklasse",
    "resources_and_spellcasting": "4 vorbereitete Zauber; Plätze 3"
  },
  {
    "ruleset": "2024/SRD-5.2.1",
    "class_id": "rogue",
    "class_de": "Schurke",
    "level": 1,
    "proficiency_bonus": 2,
    "primary": "Geschicklichkeit",
    "priority": "GE > KO > WE oder IN > CH",
    "hit_die": "W8",
    "fixed_hp_gain": "5 + KO-Modifikator",
    "saving_throws": "Geschicklichkeit, Intelligenz",
    "armor": "Leichte Rüstung",
    "weapons": "2014: einfache plus ausgewählte; 2024: einfache und Kriegswaffen mit Finesse oder Leicht",
    "skill_choices": "4: Akrobatik, Athletik, Täuschen, Motiv erkennen, Einschüchtern, Nachforschungen, Wahrnehmung, Überzeugen/Auftreten, Fingerfertigkeit oder Heimlichkeit",
    "features": "Expertise; Hinterhältiger Angriff; Diebeszeichen; Waffenmeisterschaft",
    "resources_and_spellcasting": "Hinterhältiger Angriff 1W6; 2 Meisterschaften"
  },
  {
    "ruleset": "2024/SRD-5.2.1",
    "class_id": "rogue",
    "class_de": "Schurke",
    "level": 2,
    "proficiency_bonus": 2,
    "primary": "Geschicklichkeit",
    "priority": "GE > KO > WE oder IN > CH",
    "hit_die": "W8",
    "fixed_hp_gain": "5 + KO-Modifikator",
    "saving_throws": "Geschicklichkeit, Intelligenz",
    "armor": "Leichte Rüstung",
    "weapons": "2014: einfache plus ausgewählte; 2024: einfache und Kriegswaffen mit Finesse oder Leicht",
    "skill_choices": "4: Akrobatik, Athletik, Täuschen, Motiv erkennen, Einschüchtern, Nachforschungen, Wahrnehmung, Überzeugen/Auftreten, Fingerfertigkeit oder Heimlichkeit",
    "features": "Raffinierte Aktion",
    "resources_and_spellcasting": "Hinterhältiger Angriff 1W6"
  },
  {
    "ruleset": "2024/SRD-5.2.1",
    "class_id": "rogue",
    "class_de": "Schurke",
    "level": 3,
    "proficiency_bonus": 2,
    "primary": "Geschicklichkeit",
    "priority": "GE > KO > WE oder IN > CH",
    "hit_die": "W8",
    "fixed_hp_gain": "5 + KO-Modifikator",
    "saving_throws": "Geschicklichkeit, Intelligenz",
    "armor": "Leichte Rüstung",
    "weapons": "2014: einfache plus ausgewählte; 2024: einfache und Kriegswaffen mit Finesse oder Leicht",
    "skill_choices": "4: Akrobatik, Athletik, Täuschen, Motiv erkennen, Einschüchtern, Nachforschungen, Wahrnehmung, Überzeugen/Auftreten, Fingerfertigkeit oder Heimlichkeit",
    "features": "Schurkenunterklasse; Ruhiges Zielen",
    "resources_and_spellcasting": "Hinterhältiger Angriff 2W6; Unterklasse"
  },
  {
    "ruleset": "2024/SRD-5.2.1",
    "class_id": "sorcerer",
    "class_de": "Zauberer",
    "level": 1,
    "proficiency_bonus": 2,
    "primary": "Charisma",
    "priority": "CH > KO > GE > WE",
    "hit_die": "W6",
    "fixed_hp_gain": "4 + KO-Modifikator",
    "saving_throws": "Konstitution, Charisma",
    "armor": "Keine",
    "weapons": "2014 eingeschränkte Liste; 2024 einfache Waffen",
    "skill_choices": "2: Arkane Kunde, Täuschen, Motiv erkennen, Einschüchtern, Überzeugen oder Religion",
    "features": "Zauberwirken; Angeborene Zauberei",
    "resources_and_spellcasting": "4 Zaubertricks; 2 vorbereitete Zauber; Plätze 2; Angeborene Zauberei 2/LR"
  },
  {
    "ruleset": "2024/SRD-5.2.1",
    "class_id": "sorcerer",
    "class_de": "Zauberer",
    "level": 2,
    "proficiency_bonus": 2,
    "primary": "Charisma",
    "priority": "CH > KO > GE > WE",
    "hit_die": "W6",
    "fixed_hp_gain": "4 + KO-Modifikator",
    "saving_throws": "Konstitution, Charisma",
    "armor": "Keine",
    "weapons": "2014 eingeschränkte Liste; 2024 einfache Waffen",
    "skill_choices": "2: Arkane Kunde, Täuschen, Motiv erkennen, Einschüchtern, Überzeugen oder Religion",
    "features": "Quelle der Magie; Metamagie",
    "resources_and_spellcasting": "2 Punkte; 4 vorbereitete Zauber; Plätze 3"
  },
  {
    "ruleset": "2024/SRD-5.2.1",
    "class_id": "sorcerer",
    "class_de": "Zauberer",
    "level": 3,
    "proficiency_bonus": 2,
    "primary": "Charisma",
    "priority": "CH > KO > GE > WE",
    "hit_die": "W6",
    "fixed_hp_gain": "4 + KO-Modifikator",
    "saving_throws": "Konstitution, Charisma",
    "armor": "Keine",
    "weapons": "2014 eingeschränkte Liste; 2024 einfache Waffen",
    "skill_choices": "2: Arkane Kunde, Täuschen, Motiv erkennen, Einschüchtern, Überzeugen oder Religion",
    "features": "Zaubererunterklasse",
    "resources_and_spellcasting": "3 Punkte; 6 vorbereitete Zauber; Plätze 4/2"
  },
  {
    "ruleset": "2024/SRD-5.2.1",
    "class_id": "warlock",
    "class_de": "Hexenmeister",
    "level": 1,
    "proficiency_bonus": 2,
    "primary": "Charisma",
    "priority": "CH > KO > GE > WE",
    "hit_die": "W8",
    "fixed_hp_gain": "5 + KO-Modifikator",
    "saving_throws": "Weisheit, Charisma",
    "armor": "Leichte Rüstung",
    "weapons": "Einfache Waffen",
    "skill_choices": "2: Arkane Kunde, Täuschen, Geschichte, Einschüchtern, Nachforschungen, Naturkunde oder Religion",
    "features": "Unheimliche Anrufungen; Paktmagie",
    "resources_and_spellcasting": "1 Anrufung; 2 Zaubertricks; 2 vorbereitete Zauber; 1 Platz Grad 1"
  },
  {
    "ruleset": "2024/SRD-5.2.1",
    "class_id": "warlock",
    "class_de": "Hexenmeister",
    "level": 2,
    "proficiency_bonus": 2,
    "primary": "Charisma",
    "priority": "CH > KO > GE > WE",
    "hit_die": "W8",
    "fixed_hp_gain": "5 + KO-Modifikator",
    "saving_throws": "Weisheit, Charisma",
    "armor": "Leichte Rüstung",
    "weapons": "Einfache Waffen",
    "skill_choices": "2: Arkane Kunde, Täuschen, Geschichte, Einschüchtern, Nachforschungen, Naturkunde oder Religion",
    "features": "Magische Gerissenheit",
    "resources_and_spellcasting": "3 Anrufungen; 3 vorbereitete Zauber; 2 Plätze Grad 1"
  },
  {
    "ruleset": "2024/SRD-5.2.1",
    "class_id": "warlock",
    "class_de": "Hexenmeister",
    "level": 3,
    "proficiency_bonus": 2,
    "primary": "Charisma",
    "priority": "CH > KO > GE > WE",
    "hit_die": "W8",
    "fixed_hp_gain": "5 + KO-Modifikator",
    "saving_throws": "Weisheit, Charisma",
    "armor": "Leichte Rüstung",
    "weapons": "Einfache Waffen",
    "skill_choices": "2: Arkane Kunde, Täuschen, Geschichte, Einschüchtern, Nachforschungen, Naturkunde oder Religion",
    "features": "Hexenmeisterunterklasse",
    "resources_and_spellcasting": "3 Anrufungen; 4 vorbereitete Zauber; 2 Plätze Grad 2"
  },
  {
    "ruleset": "2024/SRD-5.2.1",
    "class_id": "wizard",
    "class_de": "Magier",
    "level": 1,
    "proficiency_bonus": 2,
    "primary": "Intelligenz",
    "priority": "IN > KO > GE > WE",
    "hit_die": "W6",
    "fixed_hp_gain": "4 + KO-Modifikator",
    "saving_throws": "Intelligenz, Weisheit",
    "armor": "Keine",
    "weapons": "2014 eingeschränkte Liste; 2024 einfache Waffen",
    "skill_choices": "2: Arkane Kunde, Geschichte, Motiv erkennen, Nachforschungen, Heilkunde, Naturkunde oder Religion",
    "features": "Zauberwirken; Ritualgelehrter; Arkane Erholung",
    "resources_and_spellcasting": "3 Zaubertricks; 4 vorbereitete Zauber; Plätze 2"
  },
  {
    "ruleset": "2024/SRD-5.2.1",
    "class_id": "wizard",
    "class_de": "Magier",
    "level": 2,
    "proficiency_bonus": 2,
    "primary": "Intelligenz",
    "priority": "IN > KO > GE > WE",
    "hit_die": "W6",
    "fixed_hp_gain": "4 + KO-Modifikator",
    "saving_throws": "Intelligenz, Weisheit",
    "armor": "Keine",
    "weapons": "2014 eingeschränkte Liste; 2024 einfache Waffen",
    "skill_choices": "2: Arkane Kunde, Geschichte, Motiv erkennen, Nachforschungen, Heilkunde, Naturkunde oder Religion",
    "features": "Gelehrter",
    "resources_and_spellcasting": "5 vorbereitete Zauber; Plätze 3"
  },
  {
    "ruleset": "2024/SRD-5.2.1",
    "class_id": "wizard",
    "class_de": "Magier",
    "level": 3,
    "proficiency_bonus": 2,
    "primary": "Intelligenz",
    "priority": "IN > KO > GE > WE",
    "hit_die": "W6",
    "fixed_hp_gain": "4 + KO-Modifikator",
    "saving_throws": "Intelligenz, Weisheit",
    "armor": "Keine",
    "weapons": "2014 eingeschränkte Liste; 2024 einfache Waffen",
    "skill_choices": "2: Arkane Kunde, Geschichte, Motiv erkennen, Nachforschungen, Heilkunde, Naturkunde oder Religion",
    "features": "Magierunterklasse",
    "resources_and_spellcasting": "6 vorbereitete Zauber; Plätze 4/2"
  },
  {
    "ruleset": "2024/SRD-5.2.1",
    "class_id": "monster_hunter",
    "class_de": "Monsterjäger (Grim Hollow)",
    "level": 1,
    "proficiency_bonus": 2,
    "primary": "Stärke oder Geschicklichkeit; Intelligenz für mehrere Merkmale",
    "priority": "ST oder GE > IN > KO > WE",
    "hit_die": "W10",
    "fixed_hp_gain": "6 + KO-Modifikator",
    "saving_throws": "Stärke, Intelligenz",
    "armor": "Leichte und mittlere Rüstung, Schilde",
    "weapons": "Einfache und Kriegswaffen",
    "skill_choices": "3 aus klassenspezifischer Liste; Monsterwissen und Ermittlung priorisieren",
    "features": "Waffenmeisterschaft (2); Monstergrimoire (2 Kreaturenarten)",
    "resources_and_spellcasting": "Übungsbonus +2"
  },
  {
    "ruleset": "2024/SRD-5.2.1",
    "class_id": "monster_hunter",
    "class_de": "Monsterjäger (Grim Hollow)",
    "level": 2,
    "proficiency_bonus": 2,
    "primary": "Stärke oder Geschicklichkeit; Intelligenz für mehrere Merkmale",
    "priority": "ST oder GE > IN > KO > WE",
    "hit_die": "W10",
    "fixed_hp_gain": "6 + KO-Modifikator",
    "saving_throws": "Stärke, Intelligenz",
    "armor": "Leichte und mittlere Rüstung, Schilde",
    "weapons": "Einfache und Kriegswaffen",
    "skill_choices": "3 aus klassenspezifischer Liste; Monsterwissen und Ermittlung priorisieren",
    "features": "Kampfstil-Talent; Studierte Reaktion",
    "resources_and_spellcasting": "Reaktionskonflikte beachten"
  },
  {
    "ruleset": "2024/SRD-5.2.1",
    "class_id": "monster_hunter",
    "class_de": "Monsterjäger (Grim Hollow)",
    "level": 3,
    "proficiency_bonus": 2,
    "primary": "Stärke oder Geschicklichkeit; Intelligenz für mehrere Merkmale",
    "priority": "ST oder GE > IN > KO > WE",
    "hit_die": "W10",
    "fixed_hp_gain": "6 + KO-Modifikator",
    "saving_throws": "Stärke, Intelligenz",
    "armor": "Leichte und mittlere Rüstung, Schilde",
    "weapons": "Einfache und Kriegswaffen",
    "skill_choices": "3 aus klassenspezifischer Liste; Monsterwissen und Ermittlung priorisieren",
    "features": "Jagdgilde",
    "resources_and_spellcasting": "Schlächter-, Okkultisten- oder Fallenstellergilde"
  }
] as const;
